- Resources/bower/bower.json
This should fix the issue by pinning on version two of modernizr, v3 doesn't include modernizr.js as it has to be built.
> pin moderniz.js on version >=2.0.0 < 3.0 fixes #55

- Resources/docs/sidebar_navigation.md
- Resources/views/layout/macros.html.twig
No backward incompatibilities. Example usage:
```php
<?php
namespace MyAdminBundle\EventListener;
// ...
use Avanzu\AdminThemeBundle\Model\MenuItemModel;
use Symfony\Component\HttpFoundation\Request;
class MyMenuItemListListener {
// ...
protected function getMenu(Request $request) {
return array(
new MenuItemModel('label', 'Label', false),
);
}
// ...
}
```
> Sidebar navigation labels support

- Resources/docs/sidebar_navigation.md
- Resources/views/layout/macros.html.twig
Documentation didn't mention children menu items couldn't have icons before, so I added the functionality.
Also had to bypass a recently added restriction on sidebar navigation items requiring a route on menu item parents to show children. 
Discussion about it starts here: https://github.com/avanzu/AdminThemeBundle/issues/69#issuecomment-158660522
> Child menu item icons

- README.md
After #95 was merged-in, the `Next steps` list at the bottom of the README was missing a link to the new breadcrumb component doc.
This merge request adds this link to the empty element at the end of the list.
> Add link to breadcrumb component in README.md

- Resources/views/layout/form-theme.html.twig
Prevent a double form-control class on select field and let add classes into form builder
`
$builder->add('choice','choice', [
'attr' => [
'class' => 'select-class'
]
]);
`
> Fix class for select field

- Resources/views/layout/form-theme.html.twig
If label is set to "false" the required field is not shown. You can show it manually on placeholder or another. 
Added translation to title
> Required field only if label is defined

- Resources/views/layout/form-theme.html.twig
Setting a `'label' => false` will resolve at `{% if label is empty %}` to true, so a label cannot be disabled.
> Label of a checkbox or radio cannot be disabled

- EventListener/SetupThemeListener.php
- Resources/config/assets.php
Fix that solve unknown resource during assetic:dump 
The filename has been renamed from daterangepicker-bs3.css to daterangepicker.css
> The source file ".../web/bundles/avanzuadmintheme/vendor/adminlte/plugins/daterangepicker/daterangepicker-bs3.css" does not exist.
> [Fix] Datepicker name

- Resources/views/Partials/_scripts.html.twig
lower-case on jquery - on my systems (osx, and linux) - the jquery is lowercase.
on OSX it isn't a problem because filesystem is insensitive - but on linux (production) it is an error.
i think it is better to lowercase it.
> changing jquery to lower case

- Resources/docs/layout.md
The "How to Override Templates from Third-Party Bundles" now has a separate page in the Symfony documentation. This pr links to the new page as the old paragraph doesn't exist any more.
> Fixed Symfony doc link in layout.md

- Resources/docs/knp_menu.md
- Resources/views/Partials/_menu.html.twig
- Added support for `.header` class used in AdminLTE
- Automatically add arrows to menu items with children, just like in AdminLTE preview
- Added show/hide functionality to menu items with children by adding `.treeview-menu` class to `<ul>` tag, just like in AdminLTE preview
- Updated documentation accordingly
> Improved KnpMenu integration

- Resources/bower/bower.json
With recent versions of `bower` and `npm`, a warning is displayed upon running the `avanzu:admin:fetch-vendor` command because the `name`attribute in `bower.json`contains uppercase letters.
```
[Executing] /usr/local/bin/bower install
[Error] bower                     invalid-meta The "name" is recommended to be lowercase, can contain digits, dots, dashes
```
As mentionned in the [bower.json spec](https://github.com/bower/spec/blob/master/json.md#name) : 
>The name of the package as stored in the registry.
> - Must be unique.
> - Should be slug style for simplicity, consistency and compatibility. Example: unicorn-cake
> - **Lowercase**, a-z, can contain digits, 0-9, can contain dash or dot but not start/end with them.
> - Consecutive dashes or dots not allowed.
> - 50 characters or less.
> fix name attribute in bower.json

- Resources/views/layout/macros.html.twig
Fixes #144 by applying the `trans` filter to menu item and child labels.
> Translate menu

- Resources/views/layout/form-theme.html.twig
Using form-control on "input type=checkbox" breaks normal rendering and behavior in Chrome (didn't test FF).
The class `form-control` applies the CSS rule `appearance:none` in this line:
https://github.com/almasaeed2010/AdminLTE/blob/master/dist/css/AdminLTE.css#L1272
If you check the sources at:
https://almsaeedstudio.com/themes/AdminLTE/pages/forms/general.html
you will see, that checkboxes are not meant to use the `form-control` class.
> Fix checkbox display

- Resources/views/Sidebar/menu.html.twig
Twig > 1.28 emits a deprecation warning in `Resources/views/Sidebar/menu.html.twig` because of the way the `menu_item` macro is imported.
`Calling "menu_item" on template "AvanzuAdminThemeBundle:Sidebar:menu.html.twig" from template "AvanzuAdminThemeBundle:Sidebar:menu.html.twig" is deprecated since version 1.28 and won't be supported anymore in 2.0.
`
Twig >= 2.0 doesn't support it.
See https://github.com/twigphp/Twig/issues/2267 for a more in depth explanation.
> fix Twig deprecation in menu.html.twig

- EventListener/SetupThemeListener.php
- Resources/bower/bower.json
- Resources/config/assets.php
Fix theses errors :
[Error] bower bootflat#*          invalid-meta bootflat is missing "main" entry in bower.json
unable to process "/bundles/avanzuadmintheme/vendor/adminlte/plugins/daterangepicker/daterangepicker-bs3.css" with Error: ENOENT, no such file or directory '\bundles\avanzuadmintheme\vendor\adminlte\plugins\daterangepicker\daterangepicker-bs3.css'
> Fix errors with avanzu:admin:fetch-vendor and avanzu:admin:build-assets commands

- Resources/views/layout/base-layout.html.twig
When you use the "remember me" functionality of Symfony (and most likely the FOS User Bundle) you are getting a different role when coming back and authenticating through your cookie. Therefore I suggest to use IS_AUTHENTICATED_REMEMBERED role to also show user related content which is missing instead.
> IS_AUTHENTICATED_REMEMBERED instead of _FULLY

- Resources/views/layout/macros.html.twig
To have sub menu open, it is required to set the parent element isActive.
> Added missing isActive if child is active

- Controller/NavbarController.php
- Event/ShowUserEvent.php
- EventListener/NavbarShowUserDemoListener.php
- Model/NavBarUserLink.php
- Resources/docs/navbar_user.md
- Resources/views/Navbar/user.html.twig
- feature: adding links into widget
- feature: disabling logout and profile links
> Extended nav user widget

- Resources/views/layout/base-layout.html.twig
Not a proper fix as the base-layout.html.twig is still broken, but at least it won't causes application wide error.
Related #133
> Fixed base layout errors by just removing non existing functions

- Resources/bower/.bowerrc
I don't know why, but without this file my bower create this file structure
> Added .bowerrc

- Resources/views/layout/macros.html.twig
To correct the error that does not show the exact value of submenu labels in the sidebar menu. 
for example i tried ...
with an simple getMenu() in AdminThemeBundle/EventListener/SidebarSetupMenuDemoListener.php
We have ...
with {{ menu.menu_item_content(item, '') }}
with {{ menu.menu_item_content(child, '') }}
> Fixed macros.html.twig that does not show the exact value of submenu labels

- Event/NotificationListEvent.php
This avoid this error:
Type error: Too few arguments to function Avanzu\AdminThemeBundle\Event\NotificationListEvent::__construct(), 0 passed in /var/www/html/cti/vendor/avanzu/admin-theme-bundle/Controller/NavbarController.php on line 39 and exactly 1 expected
> Set null default value to max

- Resources/bower/bower.json
SpinJs was rewritten in TypeScript in Version 3.0 and 2.3.2 is the last version in written in JavaScript
➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖
⚠️⚠️⚠️  **THIS BUNDLE HAS ENTERED INTO ITS FEATURE FREEZE PERIOD**  ⚠️⚠️⚠️
* Pull Requests with New Features will no longer be merged.
* If you want to propose some new feature, please create an Issue.
* Pull Requests that fix bugs are still accepted and greatly appreciated.
➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖
This time, it should work
> <bugfix> Changed SpinJs version to 2.3.2

- composer.json
The current composer setup would install https://github.com/almasaeed2010/AdminLTE/tree/v2.4.2/ which is incompatible due to its changed directory structure. 
For example:
- v2.3: https://github.com/almasaeed2010/AdminLTE/tree/v2.3.11/bootstrap/css
- v2.4: https://github.com/almasaeed2010/AdminLTE/tree/v2.4.2/bower_components/bootstrap/dist/css
This PR will pin the AdminLTE version to 2.3.x 
@shakaran Can you have a look, I assume that this fix is required for the 2.0 release.
> Use AdminLTE 2.3.x (due to incompatibilities in 2.4)

- Resources/views/layout/login-layout.html.twig
Added some twig blocks, which are available in already existing in the default-layout.html.twig
- https://github.com/avanzu/AdminThemeBundle/blob/master/Resources/views/layout/default-layout.html.twig#L12
- https://github.com/avanzu/AdminThemeBundle/blob/master/Resources/views/layout/default-layout.html.twig#L351
Without these blocks we cannot easily extend the login layout.
> Support additional blocks in login layout

- Twig/AvanzuAdminExtension.php
Mini change but, sometimes bugfixes do not require many character ;-)
The boxed layout classname that can applied to the body is called `layout-boxed` instead of `boxed`.
ping @shakaran
> Bugfix for boxed layout

- Resources/views/layout/default-layout.html.twig
Hi @shakaran,
I wanted to integrate the Invoice template from the official demos: 
https://adminlte.io/themes/AdminLTE/pages/examples/invoice.html
But I failed with the `default-layout.html.twig` as I could neither change the `<section>` class name (it needs to be `invoice` instead of `content`) nor could I add the required `<div clearfix>` after the content. 
I don't need the `callout` widget on top, but thought that I add the `avanzu_page_content_before` block there as well, for the ones who want to inject some widgets before the pages main content.
I know currently its feature freeze, but it does not introduce any BC break.
I can add documentation, but wanted to ask first what you think about the proposed changes.
> Added blocks for managing the pages main content

- Resources/bower/bower.json
When tagging 1.3.9, the change that was introduced and tagged in 1.3.8 (SpinJs version lock) was lost.
This is because the FontAwesome problem was solved patching 1.3.7 instead of 1.3.8.
This pull request is trying to carry-on the simple change introduced in 1.3.8.
This would solve Issue #226 
Please, accept the request and tag as 1.3.10
> Hotfix 1.3.5

- Resources/bower/bower.json
Locks down ionicons to stable 2.0.1 as per issue #240 comments.
See this:
https://github.com/avanzu/AdminThemeBundle/issues/240
https://github.com/ionic-team/ionicons/releases?after=v4.0.0-10
> Fixes issue #240 - Locks down bower ionicons to stable 2.0.1

- Resources/bower/bower.json
Fix bootbox version.
Bootbox was created new version [5.0.0](https://github.com/makeusabrew/bootbox/tree/v5.x) and now appear error Unable to find file "@AvanzuAdminThemeBundle/Resources/public/vendor/bootbox/bootbox.js"
when execute assetic:dump command. Bootbox 5.0.0 have a different structure, and not compatible with 4.x
> fix bootbox version
